
export const ADD_PRODUCT_INTO_CART = 'ADD_PRODUCT_INTO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const ADD_QTY_TO_PRODUCT = "ADD_QTY_TO_PRODUCT"
export const REMOVE_QTY_TO_PRODUCT = "REMOVE_QTY_TO_PRODUCT"
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'