export const LOGIN_STATUS = 'LOGIN';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const UPDATE_LOADER_STATUS = 'UPDATE_LOADER_STATUS';